// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RMP3hxLPzFlpeoxMhPWzW-TudQy2-sI',
    appId: '1:58339174661:web:b9e96f1de3b2f93ae8ef6c',
    messagingSenderId: '58339174661',
    projectId: 'beattris',
    authDomain: 'beattris.firebaseapp.com',
    databaseURL: 'https://beattris-default-rtdb.firebaseio.com',
    storageBucket: 'beattris.firebasestorage.app',
    measurementId: 'G-0FRLTRWQF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgeVb1g9St6GBa_vEQ67wMTIHjlr0ehOY',
    appId: '1:58339174661:android:3ef75f2ec2f655dee8ef6c',
    messagingSenderId: '58339174661',
    projectId: 'beattris',
    databaseURL: 'https://beattris-default-rtdb.firebaseio.com',
    storageBucket: 'beattris.firebasestorage.app',
  );
}
