import 'package:cubix_blast/core/grid.dart';
import 'package:cubix_blast/core/piece.dart';

enum LastMoveType { none, move, drop, rotation }
enum TSpinType { none, mini, normal }

class CombatLogic {
  /// Detects if the current placement is a T-Spin according to the 3-corner rule.
  static TSpinType detectTSpin(CubixPiece piece, Grid grid, LastMoveType lastMove) {
    if (piece.shape != CubixShape.teeT) return TSpinType.none;
    if (lastMove != LastMoveType.rotation) return TSpinType.none;

    // Check 4 corners of the 3x3 bounding box
    int filledCorners = 0;
    
    // The T piece bounding box is essentially row..row+2, col..col+2.
    final corners = [
      Offset2D(0, 0), Offset2D(0, 2),
      Offset2D(2, 0), Offset2D(2, 2),
    ];

    int frontCornersFilled = 0;
    int backCornersFilled = 0;

    for (final corner in corners) {
      final absRow = piece.row + corner.row;
      final absCol = piece.col + corner.col;
      
      bool isFilled = false;
      if (absRow < 0 || absRow >= grid.rows || absCol < 0 || absCol >= grid.cols) {
        isFilled = true; // Wall/Floor counts as filled
      } else if (!grid.isEmpty(absRow, absCol)) {
        isFilled = true;
      }

      if (isFilled) {
        filledCorners++;
        // Determine if it's front or back based on rotation
        // r0 (pointing up): front is top (row 0), back is bottom (row 2)
        // r90 (pointing right): front is right (col 2), back is left (col 0)
        // r180 (pointing down): front is bottom (row 2), back is top (row 0)
        // r270 (pointing left): front is left (col 0), back is right (col 2)
        bool isFront = false;
        switch (piece.rotation) {
          case Rotation.r0:
            isFront = (corner.row == 0);
            break;
          case Rotation.r90:
            isFront = (corner.col == 2);
            break;
          case Rotation.r180:
            isFront = (corner.row == 2);
            break;
          case Rotation.r270:
            isFront = (corner.col == 0);
            break;
        }

        if (isFront) {
          frontCornersFilled++;
        } else {
          backCornersFilled++;
        }
      }
    }

    if (filledCorners >= 3) {
      // If 2 back corners are filled, it's a normal T-Spin.
      // If only 1 back corner is filled (but 2 front corners are), it's a Mini.
      if (backCornersFilled == 2) {
        return TSpinType.normal;
      } else {
        return TSpinType.mini;
      }
    }

    return TSpinType.none;
  }

  /// Calculates damage generated by a lock.
  static int calculateDamage({
    required int linesCleared,
    required TSpinType tSpin,
    required bool b2b,
    required int combo,
    required bool perfectClear,
  }) {
    int damage = 0;

    if (perfectClear) {
      return 10;
    }

    // Base damage
    if (tSpin == TSpinType.normal) {
      if (linesCleared == 1) {
        damage = 2; // T-Spin Single
      } else if (linesCleared == 2) damage = 4; // T-Spin Double
      else if (linesCleared == 3) damage = 6; // T-Spin Triple
    } else if (tSpin == TSpinType.mini) {
      if (linesCleared == 1) {
        damage = 1; // T-Spin Mini Single
      } else if (linesCleared == 2) damage = 4; // Very rare TSD mini, treat as normal
    } else {
      if (linesCleared == 2) {
        damage = 1;
      } else if (linesCleared == 3) damage = 2;
      else if (linesCleared == 4) damage = 4; // Tetris
    }

    // Back-to-back bonus
    if (b2b && linesCleared > 0) {
      // B2B applies to Tetris and T-Spins
      if (linesCleared == 4 || tSpin != TSpinType.none) {
        damage += 1;
      }
    }

    // Combo bonus
    if (combo > 0) {
      if (combo >= 1 && combo <= 3) {
        damage += 1;
      } else if (combo >= 4 && combo <= 6) damage += 2;
      else if (combo >= 7 && combo <= 10) damage += 3;
      else if (combo >= 11) damage += 4;
    }

    return damage;
  }
}
